title: Twitter Sentiment Analysis
description: Live twitter streaming data is classified based on its sentiment towards a given topic. This presents the live graph simulation. Done under the guidance of Dr. Gaurav Harit, Asst. Prof., IIT Jodhpur
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman
