title: Walmart Sales Forecasting
description: This project is a submission to the open problem hosted by Walmart. Concepts of Gradient boosting regression in Machine Learning is used. Done under the guidance of Dr. Vivek Vijay, Asst. Prof., IIT Jodhpur
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman
